version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

postgres:
  image: postgres:16-alpine
  container_name: postgres
  environment:
    POSTGRES_USER: ${POSTGRES_USER:-postgres}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    POSTGRES_DB: ${POSTGRES_DB:-mydb}
  volumes:
    - postgres_data:/var/lib/postgresql/data
  ports:
    - "5432:5432"
  networks:
    - app_network
  healthcheck:
    test: [ "CMD-SHELL", "pg_isready -U postgres" ]
    interval: 10s
    timeout: 5s
    retries: 5

volumes:
  postgres_data:


networks:
  app_network:
    driver: bridge
